version: '3.9'

services:
  tnl_benchmark_db:
    image: postgres:16
    container_name: tnl_benchmarks_db
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: app
    restart: unless-stopped
    command: python -m src.main
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
    depends_on:
      - tnl_benchmark_db
    volumes:
      - .:/app
volumes:
  postgres_data: